# fly.toml app configuration file generated for questly-assistant on 2024-05-27T12:19:36-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'questly-assistant'
primary_region = 'gdl'

[build]

# Define the web process (HTTP exposed)
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['web'] 

# VM resources (shared across all processes)
[[vm]]
  memory = '2048'
  cpu_kind = 'shared'
  cpus = 2

# Persisted storage for WhatsApp sessions
[mounts]
  source = "wwebjs_auth_data"
  destination = "/wwebjs_auth_data"

# Define custom process groups
[processes]
  web = "npm run start"
  worker = "npm run start:worker"
